### ISSUE TITLE
[PE-D][Tester C] archive command error

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-F12-3/tp#121]
![image.png](https://raw.githubusercontent.com/chengda300/ped/main/files/0c4ce441-1240-4cb7-bf8c-841bf9da90ab.png)

Actual: DATE is not part of arguments

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: chengda300/ped#2

**Comment by yiyefyy** [comment]
#116
