### ISSUE TITLE
[PE-D][Tester D] Description for listing tasks with deadline is wrong

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-F12-3/tp#132]
The description of listing tasks with deadline is describing listing of modules instead.

![image.png](https://raw.githubusercontent.com/jia-han/ped/main/files/04eb74e5-fa85-4052-9cb8-2dfe0461e878.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: jia-han/ped#6

**Comment by snigloo** [comment]
Closed via #179
