### ISSUE TITLE
[PE-D][Tester B] Confusing archive command output

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-F12-3/tp#165]
![image.png](https://raw.githubusercontent.com/RichDom2185/ped/main/files/ef4fa132-910a-4be4-9ef8-bee6b2b2a749.png)

The logs would say the above (invalid command), but the GUI would say task already exists in archive, removing. Unfortunately, not easily reproducible as it seems very inconsistent as to when it happens, although this may be due to poor documentation so users don't know expected behaviour and/or expected errors.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: RichDom2185/ped#10

**Comment by yiyefyy** [comment]
I tested it logger actually gives error message
